In [13]:
import numpy as np

In [14]:
a=[2,3,4,5,6,1]

In [6]:
type(a)

list

In [7]:
b=np.array([2,3,4,5,6,1])

In [8]:
type(b)

numpy.ndarray

In [26]:
a=np.array([7,9,3,5,3])
print(a.itemsize)

4


In [16]:
a=np.array([7,9,3,5,3])
a.ndim

1

In [17]:
a=np.array([[7,9,3,5,3],[5,3,2,7,6]])
print(a.shape)
a.ndim

(2, 5)


2

In [14]:
a=np.array([[7,9,3,5,3],[5,3,2,7,6]])
a=a.reshape(1,10)
a

array([[7, 9, 3, 5, 3, 5, 3, 2, 7, 6]])

In [15]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2],[8,6,1,3,8,2]])
a

array([[7, 9, 3, 5, 3, 3],
       [5, 3, 2, 7, 6, 2],
       [8, 6, 1, 3, 8, 2]])

In [22]:
a[0:4]

array([[7, 9, 3, 5, 3, 3],
       [5, 3, 2, 7, 6, 2],
       [8, 6, 1, 3, 8, 2]])

In [23]:
a[0:,1:4]

array([[9, 3, 5],
       [3, 2, 7],
       [6, 1, 3]])

In [24]:
a.sum()

83

In [16]:
a.sum(axis=0)

array([20, 18,  6, 15, 17,  7])

In [17]:
a.sum(axis=1)

array([30, 25, 28])

In [4]:
b=[5,6,7,8,9]

In [6]:
type(b)

list

In [19]:
b=np.array([2,6,78,9,10])
type(b)


numpy.ndarray

In [24]:
b=np.array([4,6,7,2,5])
print(b.itemsize)

4


In [25]:
type(b)

numpy.ndarray

In [30]:
b=np.array([[2,4,5,6,7,8],[1,23,4,5,6,8]])
b=b.reshape(2,6)
b

array([[ 2,  4,  5,  6,  7,  8],
       [ 1, 23,  4,  5,  6,  8]])

In [31]:
b=np.array([[2,4,5,6,7,8],[1,23,4,5,6,8]])
b
b[0:,2:5]

array([[5, 6, 7],
       [4, 5, 6]])

In [32]:
b.sum(axis=0)

array([ 3, 27,  9, 11, 13, 16])

In [33]:
np.sqrt(a)

array([2.64575131, 3.        , 1.73205081, 2.23606798, 1.73205081,
       2.64575131])

In [34]:
np.std(a)

2.211083193570267

In [35]:
b=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
c=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
b+c

array([[19, 15, 35, 14, 11,  4],
       [17, 14,  7, 25, 10,  4]])

In [36]:
b=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
c=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
b*c

array([[ 84,  54,  96,  45,  24,   3],
       [ 60,  33,  10, 126,  24,   4]])

In [38]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.hstack((a,b))
c

array([[ 7,  9,  3,  5,  3,  3, 12,  6, 32,  9,  8,  1],
       [ 5,  3,  2,  7,  6,  2, 12, 11,  5, 18,  4,  2]])

In [40]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.vstack((a,b))
c


array([[ 7,  9,  3,  5,  3,  3],
       [ 5,  3,  2,  7,  6,  2],
       [12,  6, 32,  9,  8,  1],
       [12, 11,  5, 18,  4,  2]])

In [42]:
a=np.array([2,8,9,12,31,4,5,17,22,9,1,23,55])
a=np.array_split(a,4)
a

[array([ 2,  8,  9, 12]),
 array([31,  4,  5]),
 array([17, 22,  9]),
 array([ 1, 23, 55])]

In [45]:
a=np.array([[2,8,9,12,31,4,5,17,22,9,1,23]])
b=np.hsplit(a,3)
b

[array([[ 2,  8,  9, 12]]),
 array([[31,  4,  5, 17]]),
 array([[22,  9,  1, 23]])]

In [47]:
a=np.array([[2,8,3,12,2,4,5,17,3,9,1,3]])
a=np.where(a%3==0)
a

(array([0, 0, 0, 0, 0], dtype=int64), array([ 2,  3,  8,  9, 11], dtype=int64))

In [48]:
x=np.rand(5,10)
print(x)

AttributeError: module 'numpy' has no attribute 'rand'