# this is my numpy ex

In [1]:
import numpy as np

In [2]:
a=np.array([7,9,3,5,3])
print(a.itemsize)

4


In [3]:
a=np.array([[7,9,3,5,3],[5,3,2,7,6]])
print(a.shape)

(2, 5)


In [33]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
a=a.reshape(3,4)
a

array([[7, 9, 3, 5],
       [3, 3, 5, 3],
       [2, 7, 6, 2]])

In [1]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2],[8,6,1,3,8,2]])
a
a[1:4,2:6]
#a[1:3,1:4]

NameError: name 'np' is not defined

In [6]:
a

array([[7, 9, 3, 5, 3, 3],
       [5, 3, 2, 7, 6, 2],
       [8, 6, 1, 3, 8, 2]])

In [44]:
a.sum(axis=0)

array([20, 18,  6, 15, 17,  7])

In [8]:
np.sqrt(a)

array([[2.64575131, 3.        , 1.73205081, 2.23606798, 1.73205081,
        1.73205081],
       [2.23606798, 1.73205081, 1.41421356, 2.64575131, 2.44948974,
        1.41421356],
       [2.82842712, 2.44948974, 1.        , 1.73205081, 2.82842712,
        1.41421356]])

In [9]:
np.std(a)

2.4069087802704967

In [10]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
a+b

array([[19, 15, 35, 14, 11,  4],
       [17, 14,  7, 25, 10,  4]])

In [46]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
a*b

array([[ 84,  54,  96,  45,  24,   3],
       [ 60,  33,  10, 126,  24,   4]])

In [11]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.hstack((a,b))
c

array([[ 7,  9,  3,  5,  3,  3, 12,  6, 32,  9,  8,  1],
       [ 5,  3,  2,  7,  6,  2, 12, 11,  5, 18,  4,  2]])

In [47]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.vstack((a,b))
c

array([[ 7,  9,  3,  5,  3,  3],
       [ 5,  3,  2,  7,  6,  2],
       [12,  6, 32,  9,  8,  1],
       [12, 11,  5, 18,  4,  2]])

In [12]:
c

array([[ 7,  9,  3,  5,  3,  3, 12,  6, 32,  9,  8,  1],
       [ 5,  3,  2,  7,  6,  2, 12, 11,  5, 18,  4,  2]])

In [49]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.concatenate((a,b),axis=1)
c

array([[ 7,  9,  3,  5,  3,  3, 12,  6, 32,  9,  8,  1],
       [ 5,  3,  2,  7,  6,  2, 12, 11,  5, 18,  4,  2]])

In [50]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
b=np.array([[12,6,32,9,8,1],[12,11,5,18,4,2]])
c=np.concatenate((a,b),axis=0)
c

array([[ 7,  9,  3,  5,  3,  3],
       [ 5,  3,  2,  7,  6,  2],
       [12,  6, 32,  9,  8,  1],
       [12, 11,  5, 18,  4,  2]])

In [60]:
a=np.array([2,8,9,12,31,4,5,17,22,9,1,23,55])
b=np.array_split(a,2)
b

[array([ 2,  8,  9, 12, 31,  4,  5]), array([17, 22,  9,  1, 23, 55])]

In [55]:
a=np.array([[2,8,9,12,31,4,5,17,22,9,1,23]])

k=np.hsplit(a,2)
k

[array([[ 2,  8,  9, 12, 31,  4]]), array([[ 5, 17, 22,  9,  1, 23]])]

In [59]:
a=np.array([[2,8,9,12,31,4,5,17,22,9,1,23]])

k=np.vsplit(a,(3,4))
k

[array([[ 2,  8,  9, 12, 31,  4,  5, 17, 22,  9,  1, 23]]),
 array([], shape=(0, 12), dtype=int32),
 array([], shape=(0, 12), dtype=int32)]

In [16]:
a=np.array([2,8,9,12,31,4,5,17,22,9,1,4,23])
b=np.where(a%2==0)
b

(array([ 0,  1,  3,  5,  8, 11], dtype=int64),)

In [17]:
mark=np.array([25,24,52,65,36,78,54,12,21,31,65])
fail_rollno=np.where(mark<35)
fail_rollno

(array([0, 1, 7, 8, 9], dtype=int64),)

In [18]:
mark=np.array([25,24,52,65,36,78,54,12,21,31,65,78])


first_mark_roll_no=np.where(mark==max(mark))
print("the roll no of students who get top mark:-",first_mark_roll_no[0])

the roll no of students who get top mark:- [ 5 11]


In [19]:
a=np.array([[7,9,3,5,3,3],[5,3,2,7,6,2]])
print(np.sort(a))

[[3 3 3 5 7 9]
 [2 2 3 5 6 7]]


In [20]:
mark=np.array([25,24,52,65,36,78,54,12,21,31,65,78])

p=mark>35

print(p)
pass_mark=mark[p]

print(pass_mark)

[False False  True  True  True  True  True False False False  True  True]
[52 65 36 78 54 65 78]


In [21]:
a=np.array([4,5,6,8])



b=a[[True,True,True,False]]

print(b)

[4 5 6]


In [22]:
c=np.array([11,4,7,2,9])

d=c[[True,False,False,True,True]]
print(d)


[11  2  9]


In [23]:
mark=np.array([25,24,52,65,36,78,54,12,21,31,65,78])

con=mark%2==0

ans=mark[con]
print(ans)

[24 52 36 78 54 12 78]


In [24]:
mark=np.array([25,24,52,65,36,78,54,12,21,31,65,78])

con=[]

for x in mark:
    if x%2==0:
        con.append(True)
        
    else:
        con.append(False)
        
        
ans=mark[con]
print(ans)

[24 52 36 78 54 12 78]


In [1]:
from numpy import random 

x=random.randint(10,101,size=(5,10))

print(x)

[[ 18  48  62  33  87  26  89  42  29  98]
 [ 91 100  37  57  47  90  21  14  70  52]
 [ 23  23 100  72  47  25  35  49  85  85]
 [ 56  84  86  54  26  88  49  10  12  41]
 [ 21  18  17  20  54  14  51  37  67  20]]


In [26]:
x=random.rand(5,10)
print(x)

[[0.7063716  0.49728928 0.59476    0.81178921 0.06170293 0.1735858
  0.67212382 0.3319209  0.7188644  0.40027441]
 [0.2992856  0.9297628  0.51378164 0.95691601 0.53339014 0.72272253
  0.06018825 0.73167929 0.08639884 0.96986236]
 [0.22464562 0.38257065 0.67348373 0.5275299  0.9958317  0.71548287
  0.19649402 0.78492352 0.23435171 0.7872738 ]
 [0.69029062 0.38541135 0.96770825 0.10744443 0.22664467 0.97961541
  0.71674844 0.4798215  0.81527076 0.72916929]
 [0.00199214 0.46879078 0.60755313 0.02134723 0.5596739  0.31643777
  0.88815424 0.6614984  0.05662414 0.57188256]]


In [68]:
c=random.choice(['Avantika','deepika','Palvi','paramjeet','harvinder'],size=(3,5))
print(c)

[['Palvi' 'Avantika' 'Avantika' 'Palvi' 'Avantika']
 ['paramjeet' 'Avantika' 'paramjeet' 'harvinder' 'deepika']
 ['paramjeet' 'paramjeet' 'deepika' 'harvinder' 'paramjeet']]


In [28]:
otp=random.randint(100000,1000000)
print("Your OTP to register/access CoWIN is ",otp)

Your OTP to register/access CoWIN is  196005


In [8]:
dat=input('enter the day')
sal=input('enter sales')
vis=input('enter visitor')
inc=input('enter income') 
exp=input('enter expenses')
value={'day':[dat],'sales':=[sal],'visitor':[vis],'income':[inc],'expenses':[exp]}

enter the day13
enter sales100
enter visitor200
enter income1000
enter expenses1500


{'day': ['13'],
 'sales': ['100'],
 'visitor': ['200'],
 'income': ['1000'],
 'expenses': ['1500']}

In [4]:
shop=value.to_csv('Sanjana_sweets.csv',index='true')

A  B  C
0  0  0  0
1  1  1  1